# Generated by Django 5.2.1 on 2025-06-10 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("doorkey", models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name="note",
            name="address",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="api.apartment",
            ),
            preserve_default=False,
        ),
    ]
