# Generated by Django 5.2.1 on 2025-06-10 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="api.tenant",
            ),
        ),
    ]
