# Generated by Django 5.2.1 on 2025-06-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_note_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="doorkey",
            field=models.CharField(max_length=255),
        ),
    ]
