# Generated by Django 5.2.1 on 2025-06-12 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_apartment_doorkey"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="address",
            new_name="apartment",
        ),
        migrations.RenameField(
            model_name="tenant",
            old_name="address",
            new_name="apartment",
        ),
    ]
