# Generated by Django 5.2.1 on 2025-06-13 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_rename_address_note_apartment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("due_at", models.DateTimeField()),
                (
                    "progress",
                    models.CharField(
                        choices=[
                            ("TO DO", "To Do"),
                            ("IN PROGRESS", "In Progress"),
                            ("DONE", "Done"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="api.apartment",
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="api.tenant",
                    ),
                ),
            ],
        ),
    ]
