# Generated by Django 5.2.1 on 2025-06-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_task_assignee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="progress",
            field=models.CharField(
                choices=[
                    ("TO DO", "To Do"),
                    ("IN PROGRESS", "In Progress"),
                    ("DONE", "Done"),
                ],
                default="TO DO",
                max_length=100,
            ),
        ),
    ]
