# Generated by Django 5.2.1 on 2025-06-17 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_chatmessage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChatMessage",
        ),
    ]
