# Generated by Django 5.2.1 on 2025-06-24 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_delete_chatmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="apartment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenants",
                to="api.apartment",
            ),
        ),
    ]
