# Generated by Django 5.2.1 on 2025-06-24 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_tenant_apartment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="apartment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="api.apartment",
            ),
        ),
    ]
